-- Add notification system tables
-- This is a reference SQL file for the notification system migration
-- Run with: npx prisma migrate dev --name add_notification_system

-- Note: This is automatically generated by Prisma based on schema.prisma
-- Keep this file for reference only

-- Notification Types Enum
CREATE TYPE "NotificationType" AS ENUM (
  'ALERT',
  'PROJECT_UPDATE',
  'PHASE_UPDATE',
  'ASSIGNMENT_CHANGE',
  'SCHEDULE_CONFLICT',
  'CAPACITY_WARNING',
  'CASH_FLOW_ALERT',
  'MONDAY_SYNC',
  'SYSTEM_MESSAGE',
  'WEEKLY_DIGEST',
  'REMINDER'
);

-- Notification Channels Enum
CREATE TYPE "NotificationChannel" AS ENUM (
  'EMAIL',
  'IN_APP',
  'PUSH',
  'SMS'
);

-- Notification Priority Enum
CREATE TYPE "NotificationPriority" AS ENUM (
  'LOW',
  'NORMAL',
  'HIGH',
  'URGENT'
);

-- Notification Status Enum
CREATE TYPE "NotificationStatus" AS ENUM (
  'PENDING',
  'QUEUED',
  'SENDING',
  'SENT',
  'DELIVERED',
  'FAILED',
  'CANCELLED'
);

-- Queue Status Enum
CREATE TYPE "QueueStatus" AS ENUM (
  'PENDING',
  'PROCESSING',
  'COMPLETED',
  'FAILED',
  'CANCELLED'
);

-- Digest Frequency Enum
CREATE TYPE "DigestFrequency" AS ENUM (
  'DAILY',
  'WEEKLY',
  'MONTHLY',
  'NEVER'
);

-- Notifications Table
CREATE TABLE "notifications" (
  "id" TEXT PRIMARY KEY,
  "user_id" TEXT NOT NULL,
  "type" "NotificationType" NOT NULL,
  "channel" "NotificationChannel" NOT NULL,
  "priority" "NotificationPriority" NOT NULL DEFAULT 'NORMAL',
  "title" TEXT NOT NULL,
  "message" TEXT NOT NULL,
  "data" JSONB,
  "template_id" TEXT,
  "template_vars" JSONB,
  "status" "NotificationStatus" NOT NULL DEFAULT 'PENDING',
  "is_read" BOOLEAN NOT NULL DEFAULT false,
  "read_at" TIMESTAMP,
  "sent_at" TIMESTAMP,
  "delivered_at" TIMESTAMP,
  "failed_at" TIMESTAMP,
  "error_message" TEXT,
  "retry_count" INTEGER NOT NULL DEFAULT 0,
  "project_id" TEXT,
  "phase_id" TEXT,
  "alert_id" TEXT,
  "action_url" TEXT,
  "action_label" TEXT,
  "expires_at" TIMESTAMP,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP NOT NULL,
  FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE
);

-- Notification Preferences Table
CREATE TABLE "notification_preferences" (
  "id" TEXT PRIMARY KEY,
  "user_id" TEXT UNIQUE NOT NULL,
  "email_enabled" BOOLEAN NOT NULL DEFAULT true,
  "in_app_enabled" BOOLEAN NOT NULL DEFAULT true,
  "push_enabled" BOOLEAN NOT NULL DEFAULT false,
  "sms_enabled" BOOLEAN NOT NULL DEFAULT false,
  "alert_notifications" BOOLEAN NOT NULL DEFAULT true,
  "project_updates" BOOLEAN NOT NULL DEFAULT true,
  "phase_updates" BOOLEAN NOT NULL DEFAULT true,
  "assignment_changes" BOOLEAN NOT NULL DEFAULT true,
  "schedule_conflicts" BOOLEAN NOT NULL DEFAULT true,
  "capacity_warnings" BOOLEAN NOT NULL DEFAULT true,
  "cash_flow_alerts" BOOLEAN NOT NULL DEFAULT true,
  "monday_sync" BOOLEAN NOT NULL DEFAULT false,
  "weekly_digest" BOOLEAN NOT NULL DEFAULT true,
  "digest_frequency" "DigestFrequency" NOT NULL DEFAULT 'WEEKLY',
  "quiet_hours_start" INTEGER,
  "quiet_hours_end" INTEGER,
  "quiet_hours_enabled" BOOLEAN NOT NULL DEFAULT false,
  "minimum_priority" "NotificationPriority" NOT NULL DEFAULT 'NORMAL',
  "batch_notifications" BOOLEAN NOT NULL DEFAULT false,
  "batch_window_minutes" INTEGER NOT NULL DEFAULT 15,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP NOT NULL,
  FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE
);

-- Notification History Table
CREATE TABLE "notification_history" (
  "id" TEXT PRIMARY KEY,
  "notification_id" TEXT NOT NULL,
  "user_id" TEXT NOT NULL,
  "channel" "NotificationChannel" NOT NULL,
  "status" "NotificationStatus" NOT NULL,
  "attempt_number" INTEGER NOT NULL,
  "sent_at" TIMESTAMP,
  "delivered_at" TIMESTAMP,
  "failed_at" TIMESTAMP,
  "error_message" TEXT,
  "provider" TEXT,
  "provider_id" TEXT,
  "metadata" JSONB,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Notification Templates Table
CREATE TABLE "notification_templates" (
  "id" TEXT PRIMARY KEY,
  "name" TEXT UNIQUE NOT NULL,
  "type" "NotificationType" NOT NULL,
  "channel" "NotificationChannel" NOT NULL,
  "subject" TEXT,
  "body_template" TEXT NOT NULL,
  "html_template" TEXT,
  "variables" TEXT[] NOT NULL,
  "language" TEXT NOT NULL DEFAULT 'en',
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "description" TEXT,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP NOT NULL
);

-- Notification Queue Table
CREATE TABLE "notification_queue" (
  "id" TEXT PRIMARY KEY,
  "notification_id" TEXT NOT NULL,
  "priority" "NotificationPriority" NOT NULL,
  "scheduled_for" TIMESTAMP NOT NULL,
  "processed_at" TIMESTAMP,
  "status" "QueueStatus" NOT NULL DEFAULT 'PENDING',
  "attempt_count" INTEGER NOT NULL DEFAULT 0,
  "max_attempts" INTEGER NOT NULL DEFAULT 3,
  "next_retry_at" TIMESTAMP,
  "error_log" TEXT,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Indexes
CREATE INDEX "notifications_user_id_idx" ON "notifications"("user_id");
CREATE INDEX "notifications_status_idx" ON "notifications"("status");
CREATE INDEX "notifications_type_idx" ON "notifications"("type");
CREATE INDEX "notifications_channel_idx" ON "notifications"("channel");
CREATE INDEX "notifications_is_read_idx" ON "notifications"("is_read");
CREATE INDEX "notifications_created_at_idx" ON "notifications"("created_at");
CREATE INDEX "notifications_priority_status_idx" ON "notifications"("priority", "status");

CREATE INDEX "notification_history_notification_id_idx" ON "notification_history"("notification_id");
CREATE INDEX "notification_history_user_id_idx" ON "notification_history"("user_id");
CREATE INDEX "notification_history_channel_idx" ON "notification_history"("channel");
CREATE INDEX "notification_history_status_idx" ON "notification_history"("status");
CREATE INDEX "notification_history_created_at_idx" ON "notification_history"("created_at");

CREATE INDEX "notification_templates_type_idx" ON "notification_templates"("type");
CREATE INDEX "notification_templates_channel_idx" ON "notification_templates"("channel");
CREATE INDEX "notification_templates_is_active_idx" ON "notification_templates"("is_active");

CREATE INDEX "notification_queue_status_idx" ON "notification_queue"("status");
CREATE INDEX "notification_queue_priority_idx" ON "notification_queue"("priority");
CREATE INDEX "notification_queue_scheduled_for_idx" ON "notification_queue"("scheduled_for");
CREATE INDEX "notification_queue_next_retry_at_idx" ON "notification_queue"("next_retry_at");
